[package]
name = "kagi"
version = "0.1.0"
edition = "2024"

[dependencies]
gpui.workspace = true
ui = { path = "../ui" }
backend = { path = "../backend" }
anyhow.workspace = true
smol.workspace = true
