[package]
name = "gst_backend"
version = "0.1.0"
edition = "2024"

[dependencies]
gstreamer.workspace = true
anyhow.workspace = true
backend = { path = "../../backend" }
gstreamer-pbutils = "0.23.4"
tokio.workspace = true
async-trait.workspace = true
