[package]
name = "reyvr"
version = "0.1.0"
edition = "2024"

[dependencies]
gpui.workspace = true
ui = { path = "../ui" }
backend = { path = "../backend" }
gst_backend = { path = "../backends/gstreamer" }
anyhow.workspace = true
